travis:
  secure:
    BINSTAR_TOKEN: Ws8MCYdZdERWbZPHMOlY25vYNTGw62IY/pVHlIqSjmJbxiPGX7j2HW3JOyD7ml11vPwpw5OTW1X2pLrULcoGT4XcLR9rBdlGhPh4otuV/3wv2TIKzC51u23ip1dhAMtKwaZu0Pl3hDU1NMKpq+rN9BRnsWGqXgjX8aX6ICsUUEiUyc8uZZf5Gq3XvAs5NQBAZjWYot2fc2K0zX0JCBCWUzlsnooMa4PnCfG6reAqLi4jNkXjZGhs38zoGdJhk8GVj0tIP2RvvnhL+KJmm51CZt9nJVKpsa6Feumi1mwf6Lyi2o4u7mpOPYMoeNk11BHMwJixsTiz0mOOl6h79dBRvcpLagR7ibttHpdNXB6YtDZibrM2M61KIrGcaz1YnIhFqITE3/1EZV8jkLck9KPhcKHgLbxIFjMOZguGl5fuqwnmo1Vovv00ZX46/7pY53pwDlttL8v3YyxXPgYo6iXcU0pWyeeI4c2w+4mjWwzbj2CuKAdtdGm5ZdF1Wk7pJfJ34l6Oe5hAEJhIQsBQjZQC5knJLr6/q5QdR5GQvbXeXB9heQc5N6OGiJIwjvjaNgTl4vEDyRN7BfV5fKImoUtvRP2zPcK6xExmJzZkLp2jh5KhCdZ/exM+TE9U3XRvY1eeeqDKaohI+YjeimDlkVuagfhK9rHHF4swf5ddNnoR+B4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
