travis:
  secure:
    BINSTAR_TOKEN: qTH4EpxyXoDSMUg8asUU6mnIXTsPNuwBbIR8Jve6nxMu2kuXPgQwBC4Bh2rG/jExRf4J2L7PxIllatJ+S3RgC/JtYZ1UQ6SVRtOxAb0Ns3Qf0kb2xpu0hRU9jJlIBRxsZkV7U/f44w4Iomf75fQl28NhsVrmeaUTQ1nkbA8ihQcR+cuzZQPO96SE3m+ci0bDw90rZv93MeXIw+PvC5yV9Di0jgyrFOtyfQGkO/dcwc32KH+kAA0vKliDCMUYTV4zvNgmDJqvhpvu/e+UFIIUIvXn03jcg9qRW6ttJwuho/P4Ytl/TwAj3tnLVudHGFhnvLvdr9/CCnynIS+M5tP/HA8PDzzjk9Oq6rQrhovXJYaXkTo525AfgDsrlT1vmbGL2gJak+pY9JaNiCDA7mQS2ulUj2Zwpj00P/p3SK3ClhM8oQTPx6c/MvBONxOgjPOLHwwqwVkAiNwFT5uQUzci9jUYO7+hEKVz7bRhHDKHjeuOwsmi/niBW8as/V1TNGidKO9czernI7lHenJnkNGOaWOQFBNc7BBSaQVACnCIUT/uSKnghOF68jby4jA+IjkiFgSpp42WXDL/XhFtXmRX5Io7+EwPer0j9fMHuvGIGMUYLAxwV2W/f/+E79+zQIOLqXy34Dg5c/hpprKS5Aozlj+mj64t+1S27NYfgvDs3Pg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
